---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: cp-quickstart
spec:
  ports:
  - port: 29092
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: broker
  namespace: cp-quickstart
spec:
  serviceName: "kafka"
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:3.2.0@sha256:82cb7a49161705ea750f3466700cce7a57e45d772f4bdbcddcdaac336dac77c0
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:32181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker-0.kafka.cp-quickstart.svc.cluster.local:29092
        ports:
        - containerPort: 29092
